---
# Use Ubuntu14.04 Server LTS
sudo: required
dist: trusty

language: python
python: "2.7"

env:
  - SITE=test.yml

#  matrix:
#    - SITE=test.yml
#    - SITE=test2.yml

before_install:
  - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ trusty main universe"
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - pip install ansible==1.9.4

  # Add ansible.cfg to pick up roles path.
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

  # Install dependencies.
  - ansible-galaxy install yaegashi.blockinfile

#  cache:
#    directories:
#      - ../yaegashi.blockinfile

before_script:
  # Uninstall rvm because failed to install Ruby
  # by issuing the following error when run playbook test.
  # --------------------
  # ./tool/rbinstall.rb:728:in `chmod': Operation not permitted @ chmod_internal
  # - /usr/local/rvm/gems/ruby-2.2.3/ (Errno::EPERM)
  # --------------------
  - rvm implode --force > /dev/null 2>&1

  # [debug] Show home directory
  - ls -lah ~
  #- cat ~/.profile
  #- cat ~/.bashrc

  # [debug] Show before interep version
  - rbenv versions
  - ruby --version
  - luaenv versions
  - lua -v
  - pyenv versions
  - python -V
  - plenv versions
  - perl -v

  # [debug] Show ansible
  #- ansible --version

  # [debug] Show current directory
  - pwd
  #- ls -lah
  #- cat ansible.cfg

  #- readlink -f ~
  #- readlink -f $HOME

  # [debug] Show login shell
  #- echo $SHELL
  #- cat /etc/shells
  #- ls -la /bin/bash

script:
  # Check the role/playbook's syntax.
  - "ansible-playbook -i tests/inventory tests/$SITE --syntax-check"

  # Run the role/playbook with ansible-playbook.
  - "ansible-playbook -i tests/inventory tests/$SITE --connection=local -vvvv"

  # Run the role/playbook again, checking to make sure it's idempotent.
  - >
    ansible-playbook -i tests/inventory tests/$SITE --connection=local -vvvv
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

after_success:


after_failure:


after_script:
  # [debug] Show after home directory
  #- ls -lah ~
  #- cat ~/.profile
  #- cat ~/.bashrc

  # [debug] Show anyenv version
  - source ~/.bashrc
  - anyenv version

  # [debug] Show interep version
  - rbenv versions
  - ruby --version
  - luaenv versions
  - lua -v
  - pyenv versions
  - python -V
  - plenv versions
  - perl -v


