---
# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"


- include: setup-RedHat.yml
  when: ansible_os_family == "RedHat"


- include: setup-Debian.yml
  when: ansible_os_family == "Debian"


- name: Install anyenv
  git:
    repo: "{{ anyenv_repository_url }}"
    dest: "{{ anyenv_installaton_dir }}"


- name: Install anyenv-plugins
  git:
    repo: "{{ item.repository_url }}"
    dest: "{{ anyenv_plugins_installation_dir }}/{{ item.name }}"
  with_items:
    - "{{ anyenv_plugins }}"


- name: Add path to profile
  blockinfile:
    dest: "{{ anyenv_export_profile_to_add_path }}"
    block: "{{ anyenv_export_block }}"
    insertafter: EOF
  when: anyenv_export


- name: Update anyenv
  tags: anyenv
  shell: |
    /bin/bash -lc "source {{ anyenv_export_profile_to_add_path }}"
    /bin/bash -lc "anyenv update"
  register: result
  changed_when: false


# When added -s option, **env will skip the installation.
- name: Install envs
  shell: |
    /bin/bash -lc "source {{ anyenv_export_profile_to_add_path }}"
    /bin/bash -lc "anyenv install -s {{ item.name }}"
  register: result
  changed_when:
    - result.stdout != ""
    - result.stderr != ""
  with_items:
    - "{{ anyenv_envs }}"


# Can't include by with_items on Ansible 1.9.x.
- include: "pyenv.yml"
- include: "luaenv.yml"
- include: "rbenv.yml"


