---
# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install anyenv
  git:
    repo: "{{ anyenv_repository_url }}"
    dest: "{{ anyenv_install_dir }}"

- name: Write path to profile
  blockinfile:
    dest: "{{ anyenv_export_to_profile }}"
    block: "{{ anyenv_export_text }}"
  when: anyenv_export

- name: Install envs
  command: "anyenv install {{ item }}"
  with_items: "{{ anyenv_installable_env_list }}"
  when: anyenv_install_{{ item }}


