---
# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install dependency libraries
  include: "setup-{{ ansible_os_family }}.yml"

- name: Install anyenv
  git:
    repo: "{{ anyenv.repository_url }}"
    dest: "{{ anyenv.install_dir }}"

- name: Add path to profile
  blockinfile:
    dest: "{{ anyenv.profile_to_add_path }}"
    block: "{{ anyenv.export_text }}"
    insertafter: EOF
  when: anyenv.export

# When added -s option, **env will skip the installation.
- name: Install envs
  shell: |
    /bin/bash -lc "source {{ anyenv.profile_to_add_path }}"
    /bin/bash -lc "anyenv install -s {{ item.name }}"
  register: result
  changed_when: result.stdout != "" and result.stderr != ""
  with_items: "{{ anyenv.envs }}"

- name: Install language
  shell: |
    /bin/bash -lc "source {{ anyenv.profile_to_add_path }}"
    /bin/bash -lc "{{ item.0.name }} install -s {{ item.1 }}"
  register: result
  changed_when: result.stdout != "" and result.stderr != ""
  with_subelements:
    - "{{ anyenv.envs }}"
    - "installation_versions"


