---
# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install anyenv
  git:
    repo: "{{ anyenv_repository_url }}"
    dest: "{{ anyenv_install_dir }}"

- name: Add path to profile
  blockinfile:
    dest: "{{ anyenv_profile_to_add_path }}"
    block: "{{ anyenv_export_text }}"
    insertafter: EOF
  when: anyenv_export

#- name: Check installed envs
#  shell: |
#    source "{{ anyenv_profile_to_add_path }}" > /dev/null 2>&1
#    anyenv version
#  changed_when: false
#  register: result_check_envs

# -sオプションで既にインストールされているならスキップする
- name: Install envs
  shell: |
    source "{{ anyenv_profile_to_add_path }}"
    anyenv install -s "{{ item }}"
  register: result
  changed_when: result.stdout != "" and result.stderr != ""
  with_items: "{{ anyenv_installable_env_list }}"
  when: anyenv_install_{{ item }}

#  shell: /bin/bash "-lc source {{ anyenv_profile_to_add_path }} && anyenv install -s {{ item }}"
#
#   source "{{ anyenv_profile_to_add_path }}"
#   /bin/bash -lc export PATH="{{ anyenv_install_dir }}/bin:$PATH"
#   /bin/bash -lc eval "$(anyenv init -)"

