---
# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install anyenv
  git:
    repo: "{{ anyenv_repository_url }}"
    dest: "{{ anyenv_install_dir }}"

- name: Add path to profile
  blockinfile:
    dest: "{{ anyenv_profile_to_add_path }}"
    block: "{{ anyenv_export_text }}"
    insertafter: EOF
  when: anyenv_export

# -sオプションで既にインストールされているならスキップする
- name: Install envs
  command: |
      source "{{ anyenv_profile_to_add_path }}"
      anyenv install -s "{{ item }}"
  with_items: "{{ anyenv_installable_env_list }}"
  when: anyenv_install_{{ item }}


