---
# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install anyenv
  git:
    repos: https://github.com/riywo/anyenv
    dist: ~/.anyenv

- name: Path
  blockinfile:
    dest: {{ anyenv_export_to_profile }}
    block: {{ anyenv_export_text }}
  when: {{ anyenv_export }}

- name: Install envs
  command: "anyenv install {{ item }}"
  when: "anyenv_install{{ item }}"
  with_items: anyenv_installable_env_list


